#!/bin/sh

docker run \
  -it \
  --rm \
  -p 8080:8080 \
  -v $(pwd)/airflow_home/:/home/home_server/airflow \
  -e HOMESERVER_ADDITIONAL_PIP_PACKAGES="pandas==1.3.5 webdav4==0.9.3" \
  -e AIRFLOW__CORE__SQL_ALCHEMY_CONN=$POSTGRESQL_CONNECTION_STRING \
  airflow-homeserver

